spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true